### ISSUE TITLE
Support https://console.cdc.cloud.sap

### ISSUE THREAD

**Issue by ohados** [SAP/sap-customer-data-cloud-toolkit#42] opened 2023-12-25 09:22 UTC
Please support also https://console.cdc.cloud.sap/url and not only https://console.gigya.com/

**Comment by bmmsantos** [comment] 2024-06-07 09:34
The issue is fixed on release 1.7.0
https://github.com/SAP/sap-customer-data-cloud-toolkit/releases/tag/1.7.0

**Closed by bmmsantos** 2024-06-07 09:34 UTC
