### ISSUE TITLE
Support Fiori Morning Horizon light

### ISSUE THREAD

**Issue by ohados** [SAP/sap-customer-data-cloud-toolkit#40] opened 2023-12-19 10:25 UTC
For an unknown reason, the addon moves the user to the Quartz light theme and there is no support for Fiori Morning Horizon light. It is important to make sure there is support because we are in transfer process and soon there will be a deprecation to the Quartz theme.

**Comment by bmmsantos** [comment] 2024-06-07 09:33
The issue is fixed on release 1.7.0
https://github.com/SAP/sap-customer-data-cloud-toolkit/releases/tag/1.7.0

**Closed by bmmsantos** 2024-06-07 09:33 UTC
