### ISSUE TITLE
Support *.my.console.[datacenter].gigya.com

### ISSUE THREAD

**Issue by luismarques-io** [SAP/sap-customer-data-cloud-toolkit#53] opened 2024-02-28 17:43 UTC
Support `*.my.console.[datacenter].gigya.com*` and not only `https://console.gigya.com/`. 
For example, the extension isn't enabled for `https://pmidce2.my.console.gigya.com/`.

![image](https://github.com/SAP/sap-customer-data-cloud-toolkit/assets/2077818/0371f483-4837-4f59-9da9-1aabe8edf2a2)

**Comment by bmmsantos** [comment] 2024-06-07 09:35
The issue is fixed on release 1.7.0
https://github.com/SAP/sap-customer-data-cloud-toolkit/releases/tag/1.7.0

**Closed by bmmsantos** 2024-06-07 09:35 UTC
